const Seed_Data = {
    products: [
        {
            _id: '1',
            name: "Product 1",
            slug: "product-1",
            category: "Category 1",
            image: "http://placekitten.com/200/100",
            price: 100,
            countInStock: 10,
            brand: "Brand 1",
            rating: 4.5,
            numReviews: 10,
            description: "Description 1"
        },
        {
            _id: '2',
            name: "Product 2",
            slug: "product-2",
            category: "Category 1",
            image: "http://placekitten.com/200/200",
            price: 150,
            countInStock: 0,
            brand: "Brand 2",
            rating: 4.0,
            numReviews: 8,
            description: "Description 2"
        },
        {
            _id: '3',
            name: "Product 3",
            slug: "product-3",
            category: "Category 2",
            image: "http://placekitten.com/200/250",
            price: 200,
            countInStock: 0,
            brand: "Brand 3",
            rating: 4.8,
            numReviews: 17,
            description: "Description 3"
        },
        {
            _id: '4',
            name: "Product 4",
            slug: "product-4",
            category: "Category 3",
            image: "http://placekitten.com/200/300",
            price: 250,
            countInStock: 15,
            brand: "Brand 4",
            rating: 4.5,
            numReviews: 14,
            description: "Description 4"
        },
        {
            _id: '5',
            name: "Product 5",
            slug: "product-5",
            category: "Category 3",
            image: "http://placekitten.com/200/350",
            price: 300,
            countInStock: 5,
            brand: "Brand 5",
            rating: 4.5,
            numReviews: 10,
            description: "Description 5"
        },
        {
            _id: '6',
            name: "Product 6",
            slug: "product-6",
            category: "Category 2",
            image: "http://placekitten.com/200/400",
            price: 350,
            countInStock: 12,
            brand: "Brand 6",
            rating: 4.5,
            numReviews: 15,
            description: "Description 6"
        },
        {
            _id: '7',
            name: "Product 7",
            slug: "product-7",
            category: "Category 1",
            image: "http://placekitten.com/200/450",
            price: 400,
            countInStock: 10,
            brand: "Brand 7",
            rating: 4.5,
            numReviews: 10,
            description: "Description 7"
        },
        {
            _id: '8',
            name: "Product 8",
            slug: "product-8",
            category: "Category 1",
            image: "http://placekitten.com/200/500",
            price: 450,
            countInStock: 0,
            brand: "Brand 8",
            rating: 4.5,
            numReviews: 17,
            description: "Description 8"
        },
        {
            _id: '9',
            name: "Product 9",
            slug: "product-9",
            category: "Category 2",
            image: "http://placekitten.com/200/550",
            price: 500,
            countInStock: 15,
            brand: "Brand 9",
            rating: 4.5,
            numReviews: 14,
            description: "Description 9"
        },
        {
            _id: '10',
            name: "Product 10",
            slug: "product-10",
            category: "Category 3",
            image: "http://placekitten.com/200/600",
            price: 550,
            countInStock: 5,
            brand: "Brand 10",
            rating: 4.5,
            numReviews: 10,
            description: "Description 10"
        },
        {
            _id: '11',
            name: "Product 11",
            slug: "product-11",
            category: "Category 3",
            image: "http://placekitten.com/200/650",
            price: 600,
            countInStock: 12,
            brand: "Brand 11",
            rating: 4.5,
            numReviews: 15,
            description: "Description 11"
        },
        {
            _id: '12',
            name: "Product 12",
            slug: "product-12",
            category: "Category 2",
            image: "http://placekitten.com/200/700",
            price: 650,
            countInStock: 10,
            brand: "Brand 12",
            rating: 4.5,
            numReviews: 10,
            description: "Description 12"
        }
    ]
}

export default Seed_Data;